{% set name = "getdaft" %}
{% set version = "0.2.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/getdaft-{{ version }}.tar.gz
  sha256: 1389ef47caa61f0daf3217b4bd5042b50e854bfb1315b104341110c09a6c072f

build:
  skip: true  # [py<37]
  script:
    - set OPENSSL_DIR=%LIBRARY_PREFIX%  # [win]
    - set OPENSSL_NO_VENDOR=1  # [win]
    - export OPENSSL_DIR=${PREFIX}  # [unix]
    - export OPENSSL_NO_VENDOR=1  # [unix]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }} 1.77
    - pkg-config
    - make
  host:
    - python
    - maturin >=1.2.0,<1.3.0
    - pip
    - openssl
    - xz
  run:
    - python
    - pyarrow >=7.0.0
    - fsspec
    - tqdm
    - typing-extensions >=4.0.0  # [py<310]
    - pickle5 >=0.0.12  # [py<38]

test:
  imports:
    - daft
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.getdaft.io/
  dev_url: https://github.com/Eventual-Inc/Daft
  doc_url: https://www.getdaft.io/projects/docs/
  summary: Distributed Dataframes for Multimodal Data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
